apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  selector:
    matchLabels:
      app: mongo     # has to match .spec.template.metadata.labels
  serviceName: mongo-headless
  replicas: 1    # by default is 1
  template:
    metadata:
      labels:
        app: mongo     # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongo
        image: docker.io/library/mongo:7.0
        ports:
        - containerPort: 27017
          name: web
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: ""
        volumeMounts:
        - name: www
          mountPath: data/db
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp3
      resources:
        requests:
          storage: 1Gi