apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    app: mongo
spec:
  type: clusterIP
  ports:
  - port: 27017
    targetPort: 27017
    name: web
  clusterIP: None
  selector:
    app: mongo